# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Owl House Co.
logo:               '/images/general/owl-house-logo.svg'
description:        Paper Crafts & Printable Designs
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'http://owlhouse.co' # The base hostname & protocol for your site
facebook:           https://www.facebook.com/owlhouseco/
twitter:            https://twitter.com/owlhouseco
instagram:          https://www.instagram.com/owlhouse.co
pinterest:          https://www.pinterest.com/owlhouseco
etsy:               https://owlhouseco.etsy.com

markdown:  kramdown
permalink: pretty
paginate:  9
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  tag

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext/

# Authors
authors:
  billy:
    name:             Billy Tamplin
    bio:              Founder of Owl House Co.
    gravatar:         https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:            heyowlhouse@gmail.com
    website:          http://owlhouse.co
    github_username:  btamps
    twitter_username: owlhouseco
